# A?VEN BULUT VER?TABANI AYARLARI
spring.datasource.url=jdbc:mysql://gelisim-ligi-db-taksoyy.k.aivencloud.com:13127/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin

# D?KKAT: ?ifreyi Aiven'daki kopyala butonuna basarak kopyala ve e?ittir(=) i?aretinden hemen sonraya yap??t?r!
spring.datasource.password=AVNS_RDcHyZRLIuFmdN4sulc

# Hibernate Ayarlar?
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true